package me.yui.market.model.coupon;

import lombok.Data;
import me.yui.market.coupon.enums.basic.AppSourceEnum;
import me.yui.market.model.basic.BizMeta;
import me.yui.market.model.basic.RecordInfo;
import me.yui.market.model.basic.User;
import me.yui.market.model.ext.Order;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class CouponInstance extends RecordInfo implements Serializable {
    private CouponBatch couponBatch;

    private CouponInstanceId instanceId;

    /**
     * sometimes we may modify promotion after generated by template batch
     */
    private Promotion promotion;

    private User bindUser;

    private BizMeta bizMeta;

    private CouponBatchId batchId;

    private AppSourceEnum appSourceEnum;

    private BindSerialId bindSerialId;

    private Date bindTime;

    private User useUser;

    private AppSourceEnum useAppSource;

    private Date freezeTime;

    private Date unfreezeTime;

    private Date useTime;

    private Order order;

    private Integer status;

    private Date startTime;

    private Date endTime;

    private Date createTime;

    private Date updateTime;

    private List<CouponFlowRecord> flowRecords;
}